# name: Staging Deploy

# on:
#   push:
#     pull_request: null
#     branches:
#       - master

# jobs:
#   deploy:
#     name: Deployment
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pgrimaud/action-shopify@2.1.1
#         env:
#           SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_STAGING_PASSWORD }}
#           SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STAGING_STORE_URL }}
#           SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_STAGING_THEME_ID }}
#           THEME_PATH: ${{ secrets.THEME_PATH }}
#         with:
#           args: --ignored-file=config/settings_data.json --ignored-file=locales/*
